apiVersion: apps/v1
kind: Deployment
metadata:
  name: cryptotrendnotify-frontend
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: frontend
          imagePullPolicy: Never
